name             'martinb3-wifi'
maintainer       'Martin Smith'
maintainer_email 'martin@mbs3.org'
license          'Apache 2'
description      'Installs/Configures wifi'
long_description 'Installs/Configures default for my unifi wifi cloud server'
version          '0.3.0'

depends 'apache2'
depends 'martinb3-base'
depends 'acme'
